server:
  port: 8088

spring:
  application:
    name: springconsumer-ribbon


#配置eureka客户端
eureka:
  client:
#  心跳检测
    healthcheck:
      enable: true
    service-url:
      defaultZone: http://zhangjc:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
#禁用eureka里面的ribbon
ribbon:
  eureka:
   enabled: false

springprovider1:
  ribbon:
    #禁用eureka里面的ribbon,配置ribbon的请求地址
    listOfServers: localhost:8091
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule