security:
  basic:
      enabled: true
  user:
    name: zhangjc
    password: 123456

server:
  port: 8761
eureka:
  server:
   # 关闭自我保护模式（缺省为打开）
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://zhangjc:123456@localhost:8761/eureka

# 是否从eureka获取注册信息
    fetch-registry: false
    # 是否注册到eureka（eureka本身是不需要再注册到自己的）
    register-with-eureka: false


spring:
  application:
    name: discover-eureka





